name: entebbe_dramp_terminal
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sliding_up_panel: ^2.1.1
  cupertino_icons: ^1.0.6
  weather: ^3.1.1
  location: ^6.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  toggle_switch: ^2.3.0
  flutter_beep: ^1.0.0
  data_table_2: ^2.5.15
  flutter_barcode_scanner: ^2.0.0
  encrypt: ^5.0.3
  material_dialogs: ^1.1.5
  nfc_classic_mifare:
    path: nfc_classic_mifare
  permission_handler: ^11.3.1
  loader_overlay: ^4.0.2+1
  shared_preferences: ^2.3.2
  flutter_otp_text_field: ^1.2.0
  intl_phone_number_input: ^0.7.4
  intl: ^0.19.0
  avatar_glow: ^2.0.2
  cached_network_image: ^3.4.1
  toastification: ^2.3.0
  fl_chart: ^0.69.0
  firebase_core: ^3.7.0
  # timezone: ^0.10.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.0
  googleapis_auth: ^1.6.0
  lottie: ^3.1.3
  flutterwave_standard_smart: ^1.0.4
  uuid: ^4.5.1
  extended_masked_text: ^3.0.1
  slider_button: ^2.1.0
  flutter_pos_printer_platform_image_3: ^1.2.0
  esc_pos_utils:

dependency_overrides:
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/speshologo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
